apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: portal
data:
  settings.yaml: |
    title: OpsScope Platform
    theme: dark
    headerStyle: clean

  bookmark.yaml: |
    - DevOps:
        - GitHub Repo:
            - abbr: GH
              href: https://github.com/ZiFOvO/ops-observability-platform.git
  
  services.yaml: |
    - Observability:
        - Grafana:
            href: https://grafana.opsscope.dev
            description: Dashboard and visualization
        - Prometheus:
            href: https://prometheus.opsscope.dev
            description: Metrics and targets
        - Alertmanager:
            href: https://alertmanager.opsscope.dev
            description: Alert routing and silences
        - Loki:
            href: https://loki.opsscope.dev
            description: Log aggregation
  
  widgets.yaml: |
    - resources:
        cpu: true
        memory: true
        disk: /

  kubernetes.yaml: |
    mode: cluster